server:
  port: 8762

spring:
  application:
    name: zuul-server


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

#zuul:
#  sensitive-headers: Cookie,Set-Cookie

zuul:
  sensitive-headers: Cookie, Set-Cookie

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000